apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: virtualworker-subscription
spec:
  pubsubname: reddog.pubsub
  topic: orders
  routes:
    rules:
      - match: "event.type == 'com.microsoft.reddog.ordercreated'"
        path: /orderCreated
scopes:
  - virtual-worker