apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: makeline-subscription
spec:
  pubsubname: reddog.pubsub
  topic: orders
  routes:
    rules:
      - match: "event.type == 'com.microsoft.reddog.ordercreated'"
        path: /orderCreated
      - match: "event.type == 'com.microsoft.reddog.orderstatuschanged' && has(event.data.orderStatus) && int(event.data.orderStatus) == 1"
        path: /orderStatusChangedInProgress
      - match: "event.type == 'com.microsoft.reddog.orderstatuschanged' && has(event.data.orderStatus) && int(event.data.orderStatus) == 2"
        path: /orderStatusChangedCompleted
scopes:
  - make-line-service