apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.secretstore
  namespace: reddog-retail
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    # value: ./manifests/local/branch/secrets.json
    value: /home/shadowc0de/repos/github/Azure/reddog-retail-code/manifests/local/branch/secrets.json