// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace RedDog.AccountingModel
{
    [DbContext(typeof(AccountingContext))]
    public partial class AccountingContextModel : RuntimeModel
    {
        static AccountingContextModel()
        {
            var model = new AccountingContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static AccountingContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
