// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace RedDog.AccountingModel
{
    public partial class AccountingContextModel
    {
        partial void Initialize()
        {
            var customer = CustomerEntityType.Create(this);
            var order = OrderEntityType.Create(this);
            var orderItem = OrderItemEntityType.Create(this);
            var storeLocation = StoreLocationEntityType.Create(this);

            OrderEntityType.CreateForeignKey1(order, customer);
            OrderItemEntityType.CreateForeignKey1(orderItem, order);

            CustomerEntityType.CreateAnnotations(customer);
            OrderEntityType.CreateAnnotations(order);
            OrderItemEntityType.CreateAnnotations(orderItem);
            StoreLocationEntityType.CreateAnnotations(storeLocation);

            AddAnnotation("ProductVersion", "6.0.4");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
